import { type InsiderRiskPolicy, type Control, type ControlStatus } from './types'

export const DEFAULT_POLICY: InsiderRiskPolicy = {
    status: 'Draft',
    version: 'v1.0',
    owner: 'IR Program Lead',
    approval: 'Pending GC + HR approval',
    scope: 'Employees, contractors, and trusted third parties with access to sensitive data, systems, or facilities.',
    last_reviewed: '2026-02-03',
    next_review: '2026-05-03',
    principles: [
        'Lawful, fair, and transparent handling of insider risk signals.',
        'Least intrusive monitoring with strict access controls and audit trails.',
        'Clear escalation paths with legal, HR, and privacy oversight.',
        'Documented decision-making and proportional response.',
        'Consistent triage decisions based on an approved business-impact rubric.',
    ],
    sections: [
        {
            title: 'Governance & Accountability',
            intent: 'Define program ownership, decision rights, and reporting cadence.',
            bullets: [
                'IR Steering Group chaired by Legal/HR with Security and Privacy representation.',
                'Case approvals required for elevated monitoring or investigative steps.',
                'Quarterly program review with KPI reporting to leadership.',
            ],
            owner: 'Legal + HR',
            artifacts: ['RACI matrix', 'Approval workflow', 'Quarterly KPI pack'],
        },
        {
            title: 'Detection & Monitoring',
            intent: 'Establish what is monitored, how signals are reviewed, and how privacy is protected.',
            bullets: [
                'Signals limited to approved telemetry and contextualized with business need.',
                'Alert triage within 5 business days with documented rationale.',
                'Sensitive access requires justification and audit log retention.',
            ],
            owner: 'Security Operations',
            artifacts: ['Monitoring charter', 'Signal catalog', 'Triage checklist'],
        },
        {
            title: 'Intake & Triage',
            intent: 'Capture early context and apply a consistent, business-friendly triage rubric.',
            bullets: [
                'Intake records trigger source, data sensitivity, jurisdiction, stakeholders, and initial evidence quality.',
                'Triage rubric uses Impact (Minimal–Severe), Likelihood (Unlikely–Confirmed), and Confidence (Low/Medium/High) with clear examples.',
                'Outcome choices are documented as No further action, HR/ER review, or Open investigation.',
                'SLA targets scale by environment size (e.g., Small: 5 business days, Mid: 3 days, Large: 24–48 hours).',
            ],
            owner: 'Investigations Lead',
            artifacts: ['Intake checklist', 'Triage rubric', 'Triage SLA matrix', 'Stakeholder notification map'],
        },
        {
            title: 'Investigation & Response',
            intent: 'Standardize case intake, evidence handling, and response actions.',
            bullets: [
                'Intake requires scope, jurisdiction, and legal basis.',
                'Evidence register maintained with chain-of-custody tracking.',
                'Escalations follow predefined decision gates and HR/legal review.',
            ],
            owner: 'Investigations Lead',
            artifacts: ['Case workflow', 'Evidence register', 'Decision log'],
        },
        {
            title: 'Privacy, Ethics, and Data Retention',
            intent: 'Protect employee rights and ensure proportionality and retention controls.',
            bullets: [
                'Data minimization applied to all case artifacts and exports.',
                'Retention periods enforced with erasure workflows and approvals.',
                'Ethics review required for high-impact monitoring changes.',
            ],
            owner: 'Privacy Office',
            artifacts: ['Retention schedule', 'Erasure certificate', 'Ethics checklist'],
        },
    ],
}

export const CONTROL_DOMAINS = ['Governance', 'Prevention', 'Detection', 'Response', 'Recovery']

export const DEFAULT_CONTROLS: Control[] = [
    {
        control_id: 'IR-CTRL-001',
        title: 'Insider Risk Policy Adoption',
        domain: 'Governance',
        objective: 'Ensure the policy is approved, communicated, and enforced.',
        status: 'in_progress',
        owner: 'Legal + HR',
        frequency: 'Annual review',
        evidence: 'Signed policy, awareness notice',
        last_reviewed: '2026-01-10',
        next_review: '2026-07-10',
        linked_actions: ['Finalize policy approval workflow', 'Publish employee notice'],
    },
    {
        control_id: 'IR-CTRL-002',
        title: 'Privileged Access Reviews',
        domain: 'Prevention',
        objective: 'Reduce unnecessary access to sensitive systems.',
        status: 'implemented',
        owner: 'IT Security',
        frequency: 'Quarterly',
        evidence: 'Access review logs, remediation tickets',
        last_reviewed: '2026-01-05',
        next_review: '2026-04-05',
        linked_actions: ['Quarterly access recertification', 'Privileged role clean-up'],
    },
    {
        control_id: 'IR-CTRL-003',
        title: 'Insider Signal Triage',
        domain: 'Detection',
        objective: 'Review and disposition alerts within defined SLAs.',
        status: 'planned',
        owner: 'Security Operations',
        frequency: 'Weekly',
        evidence: 'Triage queue exports, SLA report',
        last_reviewed: '2025-12-20',
        next_review: '2026-02-20',
        linked_actions: ['Define triage SLAs', 'Configure signal thresholds'],
    },
    {
        control_id: 'IR-CTRL-004',
        title: 'Case Intake & Gatekeeping',
        domain: 'Response',
        objective: 'Ensure cases meet legal and policy requirements before escalation.',
        status: 'monitored',
        owner: 'Investigations Lead',
        frequency: 'Per case',
        evidence: 'Gate approvals, case intake logs',
        last_reviewed: '2026-01-18',
        next_review: '2026-03-18',
        linked_actions: ['Standardize gate checklist', 'Improve intake templates'],
    },
    {
        control_id: 'IR-CTRL-005',
        title: 'Evidence Handling & Chain of Custody',
        domain: 'Response',
        objective: 'Maintain integrity of evidence through secure collection and logging.',
        status: 'implemented',
        owner: 'Investigations Lead',
        frequency: 'Per case',
        evidence: 'Evidence register snapshots, hash logs',
        last_reviewed: '2026-01-12',
        next_review: '2026-04-12',
        linked_actions: ['Enable evidence hashing', 'Train investigators on logging'],
    },
    {
        control_id: 'IR-CTRL-006',
        title: 'Program Training & Awareness',
        domain: 'Governance',
        objective: 'Ensure staff understand insider risk expectations and reporting paths.',
        status: 'in_progress',
        owner: 'HR + Compliance',
        frequency: 'Annual',
        evidence: 'Training completion report',
        last_reviewed: '2025-11-30',
        next_review: '2026-02-28',
        linked_actions: ['Refresh training modules', 'Launch awareness campaign'],
    },
    {
        control_id: 'IR-CTRL-007',
        title: 'Retention & Erasure Controls',
        domain: 'Recovery',
        objective: 'Apply retention limits and erasure workflows to case data.',
        status: 'planned',
        owner: 'Privacy Office',
        frequency: 'Quarterly',
        evidence: 'Erasure approvals, audit logs',
        last_reviewed: '2026-01-02',
        next_review: '2026-04-02',
        linked_actions: ['Configure retention schedules', 'Automate erasure reporting'],
    },
    {
        control_id: 'IR-CTRL-008',
        title: 'Post-Incident Lessons Learned',
        domain: 'Recovery',
        objective: 'Capture findings and feed improvements back into the program.',
        status: 'planned',
        owner: 'IR Program Lead',
        frequency: 'Per major case',
        evidence: 'Lessons learned register',
        last_reviewed: '2025-12-15',
        next_review: '2026-03-15',
        linked_actions: ['Create remediation tracking', 'Review policy updates'],
    },
]

export const CONTROL_STATUS_OPTIONS: ControlStatus[] = ['planned', 'in_progress', 'implemented', 'monitored']
