"""Add target_maturity to assessments

Revision ID: 8b0c02e381ce
Revises: 0009_registration_audit
Create Date: 2026-02-06 14:54:30.711858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8b0c02e381ce'
down_revision = '0009_registration_audit'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_third_party_assessments_assessment_id'), table_name='third_party_assessments')
    op.drop_index(op.f('ix_third_party_assessments_tenant_key'), table_name='third_party_assessments')
    op.drop_table('third_party_assessments')
    op.add_column('assessments', sa.Column('market_research_opt_in', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('assessments', sa.Column('target_maturity', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # op.create_unique_constraint('uq_list_ref_value', 'dim_list_options', ['list_ref', 'value'])
    op.drop_index(op.f('ix_dim_questions_tier'), table_name='dim_questions')
    op.drop_index(op.f('ix_fact_responses_assessment_q_id'), table_name='fact_responses')
    op.add_column('tenant_settings', sa.Column('industry_sector', sa.String(length=255), nullable=True))
    op.add_column('tenant_settings', sa.Column('employee_count', sa.String(length=64), nullable=True))
    op.alter_column('tenant_settings', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('users', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=512), nullable=True))
    op.alter_column('users', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'job_title')
    op.alter_column('tenant_settings', 'marketing_consent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('tenant_settings', 'employee_count')
    op.drop_column('tenant_settings', 'industry_sector')
    op.create_index(op.f('ix_fact_responses_assessment_q_id'), 'fact_responses', ['assessment_id', 'q_id'], unique=False)
    op.create_index(op.f('ix_dim_questions_tier'), 'dim_questions', ['tier'], unique=False)
    op.drop_constraint('uq_list_ref_value', 'dim_list_options', type_='unique')
    op.drop_column('assessments', 'target_maturity')
    op.drop_column('assessments', 'market_research_opt_in')
    op.create_table('third_party_assessments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('partner_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('partner_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('risk_tier', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('third_party_assessments_pkey'))
    )
    op.create_index(op.f('ix_third_party_assessments_tenant_key'), 'third_party_assessments', ['tenant_key'], unique=False)
    op.create_index(op.f('ix_third_party_assessments_assessment_id'), 'third_party_assessments', ['assessment_id'], unique=False)
    # ### end Alembic commands ###
